version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./compose/development/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - priority-data:/var/lib/postgresql/data/

volumes:
  priority-data: