# Generated by Django 4.1.5 on 2023-01-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name_plural': 'priorities'},
        ),
        migrations.AlterField(
            model_name='priority',
            name='type',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
