# Generated by Django 4.1.5 on 2023-01-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_priority_options_alter_priority_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('h', 'High'), ('m', 'Medium'), ('l', 'Low')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Priority',
        ),
    ]
